name: Deploy to FTPS
on:
  workflow_dispatch:
#   push:
#     branches:
#       - main
jobs:
  build:
    name: build
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - run: npm install
      - run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          path: ./.output/public
  deploy:
    name: deploy
    needs: build
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/download-artifact@v6
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          protocol: ftps
          local-dir: ./artifact/
          server-dir: ${{ secrets.SERVER_PATH_TEST }}